# Generated by Django 4.2.6 on 2024-09-10 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0002_temawiki_delete_articulo_delete_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='articuloWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('contenido', models.CharField(max_length=1024)),
                ('temaRelacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiApp.temawiki')),
            ],
        ),
    ]
